import type { Metadata } from "next";
import { Footer, Header, Toaster } from "@/components";
import "./globals.css";
import { ThemeProvider } from "@/providers";

export const metadata: Metadata = {
  title: "Portfolio | Lucas Andersson",
  description: "Generated by create next app",
  icons: [
    {
      url: "https://cdn-icons-png.flaticon.com/128/1259/1259122.png",
      fetchPriority: "high",
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-screen overflow-x-hidden bg-primaryLight dark:bg-primaryDark`}
      >
        <ThemeProvider>
          <Toaster />
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
